CREATE TYPE "GroupType" AS ENUM ('HACKER', 'LAWYER');

ALTER TABLE "TeamGroup"
ADD COLUMN "groupType" "GroupType" NOT NULL DEFAULT 'HACKER';

ALTER TABLE "DailyStatRevision"
ADD COLUMN "lawyerRealCaseCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lawyerAddedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lawyerExpertAddedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "customerServicePushCount" INTEGER NOT NULL DEFAULT 0;
