"use client";
import { FormEvent, useState } from "react";
import { formatAuditSummary, formatAuditTarget, formatAuditTime } from "./admin-display";

type Actor = { id: string; name: string; username: string };
export type AuditRow = { id: string; actorId: string; action: string; entityType: string; entityId: string; summary: string; createdAt: string; actor: Actor };
const actionNames: Record<string, string> = { MEMBER_CREATED: "添加成员", MEMBER_UPDATED: "更新成员", MEMBER_ADMIN_GRANTED: "授予管理员权限", MEMBER_ADMIN_PASSWORD_RESET: "重置管理员密码", MEMBER_ADMIN_REACTIVATED: "重新启用管理员账号", MEMBER_ADMIN_ACCESS_REVOKED: "撤销管理员权限", USER_EMPLOYMENT_UPDATED: "更新员工阶段", MEMBER_STATUS_CHANGED: "修改成员状态", MEMBER_PASSWORD_RESET: "重置密码", SELF_PASSWORD_CHANGED: "本人修改密码", DEPARTMENT_CREATED: "添加下属公司", DEPARTMENT_UPDATED: "更新下属公司", DEPARTMENT_STATUS_CHANGED: "修改下属公司状态", GROUP_CREATED: "添加小组", GROUP_UPDATED: "更新小组", GROUP_STATUS_CHANGED: "修改小组状态", GROUP_CONVERSION_STANDARDS_UPDATED: "修改岗位评级标准", CHANNEL_CREATED: "添加渠道", CHANNEL_UPDATED: "更新渠道", CHANNEL_PRICE_UPDATED: "更新渠道单价", CHANNEL_STATUS_CHANGED: "修改渠道状态", HISTORY_GROUP_UPDATED: "更新历史数据", SYSTEM_SETTINGS_UPDATED: "修改系统设置", CUSTOMER_PLAN_UPDATED: "更新客户计划", NOTIFICATION_SENT: "发布通知" };
actionNames.MEMBER_TRANSFERRED = "办理人员调动";
export function AuditLogTable({ initialLogs, actors, actions, timezone }: { initialLogs: AuditRow[]; actors: Actor[]; actions: string[]; timezone: string }) {
  const [logs, setLogs] = useState(initialLogs); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const query = new URLSearchParams(); new FormData(event.currentTarget).forEach((value, key) => { if (value) query.set(key, String(value)); }); try { const response = await fetch(`/api/admin/audit-logs?${query}`); if (!response.ok) throw new Error("加载日志失败"); setLogs(await response.json()); } catch (e) { setError(e instanceof Error ? e.message : "加载失败"); } finally { setLoading(false); } }
  return <section><div className="mb-5"><h2 className="text-2xl font-bold">操作日志</h2><p className="mt-1 text-sm text-slate-600">只读记录，帮助你知道谁在什么时候改了什么。</p></div><form onSubmit={filter} className="mb-4 grid gap-3 md:grid-cols-5"><input aria-label="开始日期" name="from" type="date" className="rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm" /><input aria-label="结束日期" name="to" type="date" className="rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm" /><select aria-label="操作人" name="actorId" className="rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">全部操作人</option>{actors.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select aria-label="操作类型" name="action" className="rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">全部操作</option>{actions.map((a) => <option key={a} value={a}>{actionNames[a] ?? a}</option>)}</select><button disabled={loading} className="rounded-md bg-slate-950 px-4 py-2.5 text-sm font-medium text-white">{loading ? "查询中…" : "筛选日志"}</button></form>{error && <p role="alert" className="mb-3 text-sm text-red-700">{error}</p>}<div className="overflow-x-auto border border-slate-200 bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-sm uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">时间</th><th className="px-4 py-3">操作人</th><th className="px-4 py-3">操作类型</th><th className="px-4 py-3">目标</th><th className="px-4 py-3">详情</th></tr></thead><tbody className="divide-y divide-slate-200">{logs.map((log) => <tr key={log.id}><td className="whitespace-nowrap px-4 py-3.5 text-slate-600">{formatAuditTime(log.createdAt, timezone)}</td><td className="px-4 py-3.5 font-medium">{log.actor.name}<span className="ml-1 text-sm font-normal text-slate-400">{log.actor.username}</span></td><td className="px-4 py-3.5 text-slate-700">{actionNames[log.action] ?? log.action}</td><td className="px-4 py-3.5 text-slate-600">{formatAuditTarget(log.entityType, log.entityId, log.summary)}</td><td className="px-4 py-3.5 text-slate-600">{formatAuditSummary(log.summary)}</td></tr>)}</tbody></table>{!logs.length && <div className="p-12 text-center text-sm text-slate-500">暂无符合条件的操作记录</div>}</div></section>;
}
