"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { BUSINESS_TIMEZONE_OPTIONS, businessTimezoneOption } from "../../lib/business-time-config";
import type { SystemSettings } from "../../lib/settings";
export function SystemSettingsForm({ settings }: { settings: SystemSettings }) {
  const router = useRouter();
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const form = new FormData(event.currentTarget); const body = { appName: form.get("appName"), timezone: form.get("timezone"), defaultReportMode: form.get("defaultReportMode"), allowMemberChannelCreation: false }; try { const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error((await response.json()).error ?? "保存失败"); setMessage("系统设置已保存并生效"); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "保存失败"); } finally { setSaving(false); } }
  const storedTimezoneIsListed = BUSINESS_TIMEZONE_OPTIONS.some((option) => option.timezone === settings.timezone);
  return <section><div className="mb-5"><h2 className="text-2xl font-bold">系统设置</h2><p className="mt-1 text-sm text-slate-600">这些设置会影响整个团队，保存后立即生效。</p></div><form onSubmit={submit} className="max-w-2xl border border-slate-200 bg-white"><div className="space-y-6 p-6"><label className="block text-sm font-medium">系统显示名称<input name="appName" defaultValue={settings.appName} required className="mt-2 w-full rounded-md border border-slate-300 px-3 py-2.5" /></label><label className="block text-sm font-medium">业务时区<select name="timezone" defaultValue={settings.timezone} className="mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-2.5">{!storedTimezoneIsListed ? <option value={settings.timezone}>{businessTimezoneOption(settings.timezone).label}</option> : null}{BUSINESS_TIMEZONE_OPTIONS.map((option) => <option key={option.timezone} value={option.timezone}>{option.label}</option>)}</select><span className="mt-1.5 block text-xs font-normal text-slate-500">顶部日期、今日待办、默认操作日期和报表时间范围都会按这里统一计算。</span></label><label className="block text-sm font-medium">默认报表模式<select name="defaultReportMode" defaultValue={settings.defaultReportMode} className="mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-2.5"><option value="cumulative">累计模式</option><option value="incremental">按发生日新增量</option></select></label><div className="rounded-md border border-blue-200 bg-blue-50 p-4"><span className="block text-sm font-medium text-blue-950">渠道创建权限已固定</span><span className="mt-1 block text-sm text-blue-800">只有公司管理员、资源部管理员和超级管理员可以新增渠道；一线成员只能选择已有渠道。</span></div>{message && <p role="status" className="rounded bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</p>}{error && <p role="alert" className="rounded bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}</div><div className="border-t border-slate-200 px-6 py-4"><button disabled={saving} className="rounded-md bg-blue-600 px-5 py-2.5 text-sm font-medium text-white disabled:opacity-60">{saving ? "保存中…" : "保存设置"}</button></div></form></section>;
}
